### ISSUE TITLE
Creating a working API

### ISSUE THREAD

**Issue by karhu1** [hcp-uw/syntext#13]
To start with, we can follow the youtube tutorial to set up a basic end point for our back end, and then request data to display on the front end.

https://youtu.be/w3vs4a03y3I?t=195

From that timestamp forward he sets up the server file using express, and then moves onto fetching the data with react. Creating this start/template would be really useful later on.

**Comment by elimelt** [comment]
Thanks to Kai we now have a working development API! (bars)

The basic rundown of how to use it is as follows:

send a GET request to 'http://localhost:3001/devapi/ex?length=~insert length here~', and an object will be sent in the response! 

If you want to give it a try, head to the root directory of your local repository on terminal and run the following commands:

<img width="360" alt="image" src="https://user-images.githubusercontent.com/98496503/213895914-6b1ca182-159e-489a-a45f-3fadd71d94af.png">

You've now started your development server! 

Next, to request data for a long snippet, open a browser and search the following URL:
http://localhost:3001/devapi/ex?length=long

and you should get something like this:
<img width="385" alt="image" src="https://user-images.githubusercontent.com/98496503/213895993-a9047160-200c-4385-bece-0fa9dc1964ce.png">

**Comment by elimelt** [comment]
We have since finished all the functionalities of our API needed for MVP. For details, check out syntext/server/documentation
