### ISSUE TITLE
Reset Button

### ISSUE THREAD

**Issue by PenguinTamer101** [hcp-uw/syntext#3]
Button the clears the user's text input.

**Comment by PenguinTamer101** [comment]
Also resets the timer

**Comment by elimelt** [comment]
This makes the most sense to implement either inside of Text-Area, or in a parent component that has access to much of the state for Text-Area. 

Before we assign someone to it, Rasmus and I need to clean up Text-Area.

**Comment by elimelt** [comment]
Resolved! Button and functionality is implemented in Game.js
