### ISSUE TITLE
Create basic shape layout of page + placeholders (without functionality)

### ISSUE THREAD

**Issue by sriyabulusu** [hcp-uw/syntext#5]
Includes logo in top left, codespace rectangle, colors.

**Comment by williameng2** [comment]
profile icon on the top right of the screen in line with the syntext logo

**Comment by williameng2** [comment]
line numbers of the left of the screen

**Comment by williameng2** [comment]
arrows for tab

**Comment by williameng2** [comment]
put a div rectangle with id="timer"

**Comment by williameng2** [comment]
put the text for the keyboard shortcuts centered on the bottom of the screen

**Comment by williameng2** [comment]
settings bar coding language

**Comment by williameng2** [comment]
settings bar methods and code length

**Comment by williameng2** [comment]
settings bar game mode

**Comment by williameng2** [comment]
reset icon

**Comment by elimelt** [comment]
Resolved! Looks great and works even better!
